name: Release, and Publish to Pip

on:
  push:
    paths:
        - 'pyproject.toml'
        - '.github/workflows/publish-to-pip.yaml'
        
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: siom79/poetry-installer@v1.1.18
        with:
          poetry-version: '1.1.18'

      - name: Configure Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
