name: Release, and Publish to Pip

on:
  push:
    paths:
        - 'pyproject.toml'
        - '.github/workflows/publish-to-pip.yaml'
        
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Poetry Install
        # You may pin to the exact commit or the version.
        # uses: knowsuchagency/poetry-install@7ed80d49910319d3e14ac262a5c81f681de48de0
        uses: knowsuchagency/poetry-install@v2
        

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Install twine
        run: pip install twine
      
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
  create-release-using-nuitka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Nuitka
        run: python3 -m pip install nuitka

      - name: Run Nuitka
        run: python3 -m nuitka --help

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Actions provide this token, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Made through GitHub actions automaticaly
          draft: false
          prerelease: false
            
            

